### ISSUE TITLE
How can I try ChatDrug?

### ISSUE THREAD

**Issue by rkakamilan** [chao1224/ChatDrug#2]
According to your arxiv preprint, Q&A GUI is found, but I can find only `task_and_evaluation` dir in this repo. Do you have a plan to make full scripts available for ChatDrug?

**Comment by chao1224** [comment]
Hi @rkakamilan,

Thank you for your interest in our work! We are cleaning the codes for calling the OpenAI API, which is expected to be released in a week.

**Comment by rkakamilan** [comment]
Thanks! Looking forward to trying it!

**Comment by chao1224** [comment]
Hi @rkakamilan,

@Jayfeather1024 and I have pushed the codes of using API for the ChatDrug task. Feel free to check.
