### ISSUE TITLE
No module named 'charset_normalizer.md__mypyc'

### ISSUE THREAD

**Issue by rkakamilan** [chao1224/ChatDrug#4]
I got the error, but solved it by installing `charset-normalizer==2.1.0` according to [here](https://stackoverflow.com/questions/74182807/no-module-named-charset-normalizer-md-mypyc).

**Comment by Jayfeather1024** [comment]
It may due to the usage of incorrect version of package `charset-normalizer`. If you follow the instructions in `README.md` to create a new virtual environment, there should not be such kind of problems.
