### ISSUE TITLE
`DBfile` in `load_retrieval_DB` not matched to README

### ISSUE THREAD

**Issue by rkakamilan** [chao1224/ChatDrug#6]
In `load_retrieval_DB` func, `DBfile` paths are specified, but the paths don't correspond to those in `data/README.md`. 

Ex) L89 should be:
```
DBfile = 'data/smale_molecule/250k_rndm_zinc_drugs_clean_3.csv'
```

**Comment by Jayfeather1024** [comment]
I'm sorry that the path was previously used in our dev version. Now I have updated the new code to align the paths with `data/README.md`.
