### ISSUE TITLE
Could you please share the code for applying the Vicuna model?

### ISSUE THREAD

**Issue by peggy-minyao** [chao1224/ChatDrug#9]
Hello！I would like to run the code once, but it seems that the ChatGPT API requires payment. I noticed that you mentioned applying the Vicuna model in your Complete function（in Conversational_LLMs_utils.py). Could you share it?

**Comment by chao1224** [comment]
Hi @peggy-minyao, thank you for the question.

We do leave a placeholder for that, and @Jayfeather1024 can help follow this.

**Comment by SaraiQX** [comment]
Hi ChatDrug team, great thanks for this amazing work.
I do have the same question as Vicuna v1.5 performs quite well. Also I recommend serving frameworks like FastChat which naturally support vicuna models and can form oepnai compatible API.

**Comment by chao1224** [comment]
Hi @SaraiQX @peggy-minyao ,

Apologize for the delay. Please check this latest commit (fb8470b81686c533fb3df1ad96cdb3405dae802d) for the galactica and llama2.
